runtime: python39
service: would-you-rather

handlers:
- url: /static
  static_dir: static
- url: /(.*\.(json|ico|js))$
  static_files: \1
  upload: build/.*\.(json|ico|js)$
- url: .*
  static_files: index.html
  upload: index.html