runtime: python39
service: would-you-rather

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/media
  static_dir: static/media
  
- url: .*
  script: auto